{% set name = "pytest-shutil" %}
{% set version = "1.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-shutil-{{ version }}.tar.gz
  sha256: d8165261de76e7508505c341d94c02b113dc963f274543abca74dbfabd021261

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-git
  run:
    - python >=3.6
    # https://github.com/man-group/pytest-plugins/blob/v{{ version }}/pytest-shutil/setup.py#L25
    - six
    - execnet
    # 'contextlib2;python_version<"3"',
    - pytest
    - path
    # 'path.py; python_version < "3.5"',
    # 'mock; python_version<"3.3"',
    - termcolor

test:
  imports:
    - pytest_shutil
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/manahl/pytest-plugins
  license: MIT
  license_family: MIT
  license_file: 'LICENSE'
  summary: A goodie-bag of unix shell and environment tools for py.test
  doc_url: https://github.com/manahl/pytest-plugins/tree/master/pytest-shutil#readme
  dev_url: https://github.com/manahl/pytest-plugins

extra:
  recipe-maintainers:
    - jcfr
    - ocefpaf
