{% set name = "pytest-shutil" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-shutil-{{ version }}.tar.gz
  sha256: aad006ef7b6efcbace1e6bdf90ea7870c4367ab917b85fbdbac1fca1df1f48a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-git
  run:
    - python >=3.6
    # https://github.com/man-group/pytest-plugins/blob/{{ version }}/pytest-shutil/setup.py
    - six
    - execnet
    - pytest
    - termcolor

test:
  imports:
    - pytest_shutil
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/man-group/pytest-plugins
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A goodie-bag of unix shell and environment tools for py.test
  doc_url: https://github.com/man-group/pytest-plugins/tree/master/pytest-shutil#readme
  dev_url: https://github.com/man-group/pytest-plugins

extra:
  recipe-maintainers:
    - jcfr
    - ocefpaf
