travis:
  secure:
    BINSTAR_TOKEN: DYUSQt2UQX5nDrheRbxm6eZKOaJS7FgTtWBhYrBG1sFe8GrwRrm6zBJePVBcbwSfuTWzppldjpuotK1kyxcUFNAJ99rbwYP6yHA12aYChGQeuMGm7qGN1+xpoaZngiXGZiCf1z8S7S3YEOhd4+leBbh/A8jKWr5XymlR9HVR0pNzXFYYFgORHXieecLqePBcM2a/xZgBBpsTlEi68vmGYCdyo7s2sjHH6nTojjwr5GHdm3PJF7H83DsoQskD13bLxjgcQedMjkbigKHyz4xL3/nzyRevh1BWnOx2aKPFX7fQgLEqxvUBmTe2QwjBnq3pJg9P+pRNSvSHB9LBHjqjmMvYtUoJsPo2r4fenBUJuE2ecUPtup8I5awsdH69RV3X93cGYzKnO/RP/7b/HlLzvgvcHE3a1xzNtwAntybWLqw/qwvPCeaa9ASdNbA/u44+YGuZDm5leW/6FXjza+DDqNZG00N0MlpBX21DyKp1Hzf3hv8vgxtiinvYL26DvNRjyxlzr1AS9hdDyphqrshPfQrm2bArniex3P5OUhDaDb7Hy0zUhOnjcMO97mLaGp24JW/x7bgrAk42CsEZh+5p4TtE66RcP5/l8AHRENGugon6VtwtmZmIUlCOySMDcO10bDXCpmZ1fw++fRoJqjWXwCcYIXqOcHaFTIF43rhE3E4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
